catalog/urls.py
from django.conf.urls import url
from . import views

app_name = 'catalog'

urlpatterns = [

	url(r'^$', views.IndexView.as_view(), name='index'),
	url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

	url(r'^categorias/([\w_-]+)/$',views.category,name='category')
]

log/urls.py
from django.conf.urls import url
from . import views

ulrpatterns = [
	url(r'^$',views.home, name='home')
]

projetoCiti/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from contac.views import  contact
from django.contrib.auth import views
from log.forms import LoginForm

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('log.urls')),
    url(r'^login/$', views.login, {'template_name': 'login.html', 'authentication_form': LoginForm}),  
    url(r'^logout/$', views.logout, {'next_page': '/login'}),  
    url(r'^catalog/', include('catalog.urls')),
    url(r'^contact/', contact, name ='contac'),
]

catalog/models.py
from django.db import models

# Create your models here.


class Category(models.Model):

    name = models.CharField('Nome', max_length=100)
    slug = models.SlugField('Slug')

    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'

    def __str__(self):
        return self.name


class CourseManager(models.Manager):

    def highlined(self):
        return self.filter(is_highline=True)


class Course(models.Model):

    name = models.CharField('Nome', max_length=100)
    slug = models.SlugField('Slug')
    category = models.ForeignKey(Category, verbose_name='Categoria')
    description = models.TextField('Descrição', blank=True)
    is_highline = models.BooleanField('Destaque', default=True, blank=True)
    price = models.DecimalField(
        'Preço', default=0, decimal_places=2, max_digits=8
    )
    objects = CourseManager()

    class Meta:
        verbose_name = 'Curso'
        verbose_name_plural = 'Cursos'

    def __str__(self):
        return self.name

contac/models.py
from django.db import models

# Create your models here.

log/models.py
from django.db import models

# Create your models here.

contac/forms.py
from django import forms

class ContactForm(forms.Form):
	name = forms.CharField(label='Nome')
	email = forms.EmailField(label='E-mail')
	massage = forms.CharField(label='Mensagem',widget=forms.Textarea())

	def clean_name(self):
		name = self.cleaned_data['name']
		if name == 'fulano':
			raise forms.ValidationError('Este não pode ser seu nome')
		return name

log/forms.py
#log/forms.py
from django.contrib.auth.forms import AuthenticationForm 
from django import forms

# If you don't do this you cannot use Bootstrap CSS
class LoginForm(AuthenticationForm):
    username = forms.CharField(label="Username", max_length=30, 
                               widget=forms.TextInput(attrs={'class': 'form-control', 'name': 'username'}))
    password = forms.CharField(label="Password", max_length=30, 
                               widget=forms.TextInput(attrs={'class': 'form-control', 'name': 'password'}))

catalog/views.py
from django.views import generic
from .models import Category, Course

# Create your views here.

class IndexView(generic.ListView):
	template_name = "catalog/index.html"
	context_object_name = "all_course"

	def get_queryset(self):
		return Course.objects.highlined()

class DetailView(generic.DetailView):
	model = Course
	template_name = "catalog/detail.html"

def category(request, slug):
	category = get_object_or_404(Category,slug=slug)
	context = {
		'category': category,
		'course':Couse.objects.filter(category=category)

	}
	return render(request,'catalog/category.html',context)

contac/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render
from django.contrib import messages
from django.http import HttpResponse
from django.core.mail import send_mail
from django.views.generic import View, TemplateView

from .forms import ContactForm

class IndexView(TemplateView):
	template_name = 'index.html'

def contact(request):
	if request.method =='POST':
		form = ContactForm(request.POST)
		if form.is_valid():
			name = form.cleaned_data['name']
			email = form.cleaned_data['email']
			messages = form.cleaned_data['messages']
			subject = '[DjangoEcommerce] %s entrou em contato' % name
			body = 'E-mail: %s\n%s' % (email, message)
			send_mail(subject,body,'admin@example.com',['contato@admin.com'])
			form = ContactForm()

		else:
			messages.error(request,'Formulário inválido')
	else:
		form = ContactForm()
	context = {

		'form':form
	}
	return render(request,'contact.html',context)

log/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required(login_url="login/")
def home(request):
	return render(request,"home.html")

catalog/templates/catalog/detail.html
<h1>{{course.name}}</h1>
<h3>{{course.category}}</h3>
fdsa

catalog/templates/catalog/index.html
<ul>
	{% for course in all_course %}

		<li><a href ="{% url 'catalog:detail' course.id %}">{{course.name}}</a></li>
		
	{% endfor %}
</ul>

contac/templates/contact.html
<div class="page-header">
    <h1>Fale conosco</h1>
    {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
        {{ error }}
    </div>
    {% endfor %}
    <form class="form-horizontal" method="post" action="">
        {% csrf_token %}
        <fieldset>
            {% for field in form %}
            <div class="form-group{% if field.errors %} has-error{% endif %}">
              <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
              <div class="col-md-9">
                {% render_field field class='form-control' %}
                {% for error in field.errors %}
                <span class="help-block">{{ error }}</span>
                {% endfor %}
              </div>
            </div>
            {% endfor %}
            <div class="form-group">
              <div class="col-md-9 col-md-offset-3">
                <button type="submit" class="btn btn-primary">Enviar</button>
              </div>
            </div>
        </fieldset>
    </form>
</div>

log/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <title>Auth Demo</title>
                <!-- Core CSS - Include with every page -->
                <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
                </head>
                <body>
                    <nav class="navbar navbar-default">
                        <div class="container-fluid">
                            <div class="navbar-header">
                                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                                    <span class="sr-only">Toggle navigation</span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                </button>
                                <a class="navbar-brand" href="#">Rocky Balbo</a>
                            </div>
                            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                                <ul class="nav navbar-nav navbar-right">
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Account
                                            <span class="caret"></span>
                                        </a>
                                        <ul class="dropdown-menu" role="menu">
                                            <li>
                                                <a href="/home">home</a>
                                            </li>
                                            <li>
                                                <a href="#">Another action</a>
                                            </li>
                                            <li>
                                                <a href="#">Something else here</a>
                                            </li>
                                            <li class="divider"></li>
                                            <li>
                                                <a href="#">Separated link</a>
                                            </li>
                                            <li class="divider"></li>
                                            <li>
                                                <a href="/logout">Logout</a>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </nav>

                {% block content %}
                {% endblock %}


                    <!-- Core Scripts - Include with every page -->
                    <script src = "{% static 'js/jquery.min.js' %}"></script>
                    <script src = "{% static 'js/bootstrap.min.js' %}"></script>
        {% block javascript %}
        {% endblock %}


            </body>
        </html>

log/templates/home.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="jumbotron">
            <h1>Hello</h1>
            <p>You are on your Dashboard</p>
        </div>
    </div>
</div>
{% endblock %}

log/templates/login.html
{% extends 'base.html' %}


{% block content %}
    {% if form.errors %}

<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}

<p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}

<p>Please login to see this page.</p>
    {% endif %}
{% endif %}

<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="login-panel panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Please Sign In</h3>
                </div>
                <div class="panel-body">
                    <form method="post" action="{% url 'django.contrib.auth.views.login' %}">
{% csrf_token %}

                        <p class="bs-component">
                            <table>
                                <tr>
                                    <td>{{ form.username.label_tag }}</td>
                                    <td>{{ form.username }}</td>
                                </tr>
                                <tr>
                                    <td>{{ form.password.label_tag }}</td>
                                    <td>{{ form.password }}</td>
                                </tr>
                            </table>
                        </p>
                        <p class="bs-component">
                            <center>
                                <input class="btn btn-success btn-sm" type="submit" value="login" />
                            </center>
                        </p>
                        <input type="hidden" name="next" value="{{ next }}" />
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block javascript %}


<script>
{% if not user.is_authenticated %}
$("ul.nav.navbar-nav.navbar-right").css("display","none");
{% endif %}
</script>

{% endblock %}